### PR TITLE
Implement round robin failover for collectd

### PR DESCRIPTION
**Pull request by hoang-tetration**
Summary:
https://tetration.atlassian.net/browse/MI-21

As a part of MI-21, this change is on the collectd. Later on, I will move this into a common place where any java code should be able to use this library.

This change extends RetryingAsyncSocket with a round robin policy and can easily extend with future policy.

Test plan:
- Unit test.
- Will deploy on euclid-2 for field testing.

Reviewers:
@vjeyakum

### CODE REVIEW

**Comment by hoang-tetration** [comment]
I ended up implementing retry of write when failure as well. It's not much but will make the write more robust. We may consider in the future some kind of buffering, if needed.

**Comment by hoang-tetration** [comment]
I still haven't committed this PR because it will make collectd ansible script not working correctly (can't compile OpenTSDB jar).

The change of ansible collectd script is in https://github.com/TetrationAnalytics/tetration/pull/942

**Comment by hoang-tetration** [comment]
Refactored. PTAL!

**Comment by hoang-tetration** [comment]
Thanks. I added the suggested comment. I agreed that we don't want to make this socket thread safe, which can make this async quite tricky. This socket is meant for writing stuff to TSDBs, not for generic use :-)

BTW, I will test this on staging first, once it's up stable and we're all at java8.

**Comment by vjeyakum** [comment]
Cool, thanks!

**Comment by hoang-tetration** [comment]
Tested and it worked. pascal-2's collectd was installed with failover tsdb socket. pascal-5's wasn't.

- pascal-2's tsdb was taken down first (the default). pascal-5's collect was affected. pascal-2's failed over to pascal-5's tsdb.  
- pascal-5's tsdb was taken down next and so both got no data.
- pascal-2 was restored, both bounced back to normal.

screen shot 2015-06-12 at 5 25 12 pm

**Comment by vjeyakum** [comment]
Ooh, I saw your last note but I didn't realise you had a picture attached. :D  Thanks so much! :+1:

**Pull request merged**
